### ISSUE TITLE
Pydantic Literal type error

### ISSUE THREAD

**Issue by bogdanaks** [piercefreeman/gpt-json#39]
Hello! Thanks for your library!

I'm trying to use Literal to validate fields, but I'm running into an error.
```
Traceback (most recent call last):
  File "/.venv/lib/python3.11/site-packages/telethon/client/updates.py", line 570, in _dispatch_update
    await callback(event)
  File "/src/services/telegram/__init__.py", line 63, in handler_new_msg
    await self.lang.parse_message(message, message_type, user)
  File "/src/services/langchain/__init__.py", line 69, in parse_message
    resume = await self.parse_resume(message.message)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/src/services/langchain/__init__.py", line 79, in parse_resume
    gpt_json = GPTJSON[ResumeSchema](
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Desktop/my/tgjobs/tgjobs-parser/.venv/lib/python3.11/site-packages/gpt_json/gpt.py", line 185, in __init__
    self.schema_prompt = generate_schema_prompt(self.schema_model)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.11/site-packages/gpt_json/prompts.py", line 46, in generate_schema_prompt
    return generate_payload(schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.11/site-packages/gpt_json/prompts.py", line 36, in generate_payload
    elif issubclass(field_annotation, BaseModel):
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen abc>", line 123, in __subclasscheck__
TypeError: issubclass() arg 1 must be a class
```

Schema I'm using:
```
class ResumeSchema(BaseModel):
    name: str = Field(
        default='',
        description="Author")
    title: str = Field(
        default='',
        description="Title")
    work_format: Literal['REMOTE', 'OFFICE', 'ANY', 'UNKNOWN'] = Field(
        default='UNKNOWN',
        description="Work format (REMOTE, OFFICE, ANY, UNKNOWN)")
```

Details:
pydantic==2.4.2

Please let me know if you have any additional questions or require additional information.

**Comment by piercefreeman** [comment]
Hey @bogdanaks, thanks for the bug report and the reproduction case. I've fixed this in https://github.com/piercefreeman/gpt-json/pull/40 and included this test case in the unit tests. It should be out on pypi soon.
